
--Table structure for table 'classification'
CREATE TABLE public. classification (

classification_id INT GENERATED BY DEFAULT AS IDENTITY, 
classification_name CHARACTER VARYING NOT NULL, 
CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);





-- Table structure for table "inventory"



CREATE TABLE IF NOT EXISTS public. inventory

(

inv_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
inv_make character varying NOT NULL,
inv_model character varying NOT NULL,
inv_year character (4) NOT NULL,
inv_description text NOT NULL, 
inv_image character varying NOT NULL,
inv_thumbnail character varying NOT NULL,
inv_price numeric (9, 0) NOT NULL,
inv_miles integer NOT NULL,
inv_color character varying NOT NULL, 
classification_id integer NOT NULL, 
descripcion VARCHAR(50) NOT NULL,
CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)

);



--Create relationship between 'classification' and 'inventory' tables
ALTER TABLE IF EXISTS public. inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id) MATCH SIMPLE
ON UPDATE CASCADE
ON DELETE NO ACTION;





















































CREATE TABLE cuentas (
    account_id SERIAL PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    account_type VARCHAR(50) DEFAULT 'Usuario',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO cuentas (first_name, last_name, email, password)
VALUES ('Tony', 'Stark', 'tony@starkent.com', 'Iam1ronM@n');


UPDATE cuentas
SET account_type = 'Administración'
WHERE first_name = 'Tony' AND last_name = 'Stark';


DELETE FROM cuentas
WHERE first_name = 'Tony' AND last_name = 'Stark';



-- 1. Modificar el registro "GM Hummer"
UPDATE inventory
SET descripcion = REPLACE(descripcion, 'small interiors', 'a huge interior')
WHERE descripcion LIKE '%GM Hummer%';

 2. Seleccionar marca, modelo y nombre de clasificación para artículos de la categoría "Deporte"
SELECT i.marca, i.modelo, c.nombre_classification
FROM inventory i
INNER JOIN classification c ON i.classification_id = c.id
WHERE c.nombre_clasificacion = 'Deporte';

-- 3. Actualizar las rutas de inv_image e inv_thumbnail
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');


